//src/components/modals/AuthenticatorVerifyCodeModal.jsx
'use client';
import React, { useState } from 'react';
import Modal from '@/components/UI/Modal';
import Button from '@/components/UI/Button';
import ResponsiveText from '@/components/UI/ResponsiveText';

export default function AuthenticatorVerifyCodeModal({ code, isOpen, onClose, error, onCodeChange = () => {} }) {
    const [localCode, setLocalCode] = useState(code && code.length ? code : ["", "", "", "", "", ""]);

    const handleChange = (index, value) => {
        const newCode = [...localCode];
        newCode[index] = value.slice(0, 1);
        setLocalCode(newCode);
        onCodeChange(newCode);
        if (value && index < 5) document.getElementById(`code-input-${index + 1}`).focus();
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            header={
                <div className="flex items-start justify-between">
                    <ResponsiveText as="h2" minSize="18px" maxSize="20px" className="text-oxford-blue font-bold">
                        Authenticator
                    </ResponsiveText>
                </div>
            }
            className="max-w-sm p-0 pb-4"
            showCloseButton={true}
        >
            <div className="grid h-full items-center gap-3">
                <p className="text-oxford-blue/80 text-sm">Enter the 6-digit code generated by your authenticator app</p>

                <div className="flex items-center gap-3">
                    {localCode.map((digit, index) => (
                        <input
                            key={index}
                            id={`code-input-${index}`}
                            type="text"
                            inputMode="numeric"
                            pattern="[0-9]*"
                            value={digit}
                            onChange={(e) => handleChange(index, e.target.value.replace(/\D/g, ''))}
                            className={`w-16 h-14 text-center rounded-md bg-ghost-white border ${
                                error && index === 0 ? 'border-red-400' : 'border-gray-200'
                            } focus:outline-none focus:ring-2 focus:ring-vivid-red text-oxford-blue text-lg`}
                            maxLength="1"
                            autoFocus={index === 0}
                        />
                    ))}
                </div>

                {error && <p className="text-red-500 text-sm mt-1">{error}</p>}

                <p className="text-oxford-blue/60 text-sm"><span className="text-oxford-blue">Tip</span>: Make Sure to check your inbox</p>

                <div>
                    <Button fullWidth variant="primary" className="rounded-md h-12 bg-vivid-red text-white">
                        Next
                    </Button>
                </div>
            </div>
        </Modal>
    );
}